#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hello: # Nom de la route
  path: /hello # Chemin qu'on retrouve dans l'url pour charger la route accueil
  controller: App\Controller\TestController::hello # Controller instancié et nom de la méthode appelée lorsque le path est "/"
  methods: ["GET"] # Methods autorisées pour charger la page